### ISSUE TITLE
Find a product name

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#1]
As "stacked" is already used for a different app, a matching name is needed.

Ideas go in different directions:
* atomic design 
* space and everything connected with the universe
* alphabetic systems
* enable users to improve their experience, design, products

**Comment by pixelass** [comment]
Just brainstorming here to inspire.

When I look for names I often try foreign languages.

Grid => Schachtel (German for "box")
Virtual DOM => Arbol (Spanish for "tree")

The languages I use are often related to the product

Grids => swiss design => german name
Trees => Rainforest => South america => spanish name

I'm not sure if this helps in any way but it's a technique I use when I want to find unique names that somehow make sense.
