### ISSUE TITLE
Opening styleguide fails

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#101]
When I try to open a styleguide with the open-link from the splash screen, the Alva app freezes.

### Steps to reproduce
1. Quit Alva
2. Rename the designkit folder
3. Open Alva

The developer is attached as image:
<img width="581" alt="bildschirmfoto 2017-12-20 um 20 42 59" src="https://user-images.githubusercontent.com/8946766/34225333-6615218c-e5c6-11e7-8f18-c2355eaf20dd.png">

**Comment by LKuechler** [comment]
We should check if the styleguide exists and that we have access to it with `FileUtils.accessSync` and if we don't have access we should show a error and clean the laststyleguidepath
