### ISSUE TITLE
npm start alerts that electron is missing

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#106]
I just re-cloned Alva completely. "npm i" worked fine, but after "npm start" I get this error:
<img width="547" alt="bildschirmfoto 2017-12-20 um 21 53 20" src="https://user-images.githubusercontent.com/8946766/34228232-575f3ea2-e5d0-11e7-8669-c2953f136241.png">

**Comment by LKuechler** [comment]
After removing my build folder i can reproduce this.

I will look at it in detail now
