### ISSUE TITLE
Direct Git integration

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#110]
As a designer I want to directly commit my latest design changes, and pull or push it to/from a specified repository. The same for the pattern library.
We should think about an easy-to-use integration, so that designers without huge Git knowledge can use this feature, too.

At the moment as a designer I could handle my files via an external Git tool of my choice.

## Design
How could a easy-to-use Commit/Pull/Push interface look like?

**Comment by Jumace** [comment]
I know what you want to achieve with that feature but it could be a dangerous road.

With that the application could end in a swiss army knife which includes a lightsaber and even more.
In my view Alva should only have the single responsibility it already has.

Nonetheless there would be one solution to 'rule them all':
Make Alva ready for extensions (like Atom or Visual Studio Code).
I know it's not a low hanging fruit but it would give the option to include features like git integration and many more but only for the users who want it.

Maybe you should discuss that inside the core team.

**Comment by tilmx** [comment]
@Jumace Thats a good note. Our plan is to enable extensions as you said – and that could be a good way to add these kinds of features as you mentioned. Thanks!

**Comment by tilmx** [comment]
Closed for a new issue for a better live collaboration...
