### ISSUE TITLE
Add Touchbar Support

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#112]
For the most common actions, we should integrate the Touchbar of the latest MacBook models. We should discuss about which options should be displayed there.

## Design
How should a touchbar interface for Alva look like?

**Comment by barinali** [comment]
@tilmx do we have a rough draft for touch bar items? Otherwise, I may try to come up with a first iteration of touch bar support.

**Comment by tilmx** [comment]
Hey @barinali! Not yet, to be honest. If you want to, feel free to think about it!

**Comment by yuzl** [comment]
out of scope. May be re-opened
