### ISSUE TITLE
Highlight selected page element in preview

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#129]
When I select a page element in the element pane, I want to have the selected element highlighted with an outline in the preview pane. It should look like the attached image:

![alva-element-selected](https://user-images.githubusercontent.com/8946766/34266370-20c74d9a-e679-11e7-936b-beff198fe52a.png)

**Comment by chaosmonster** [comment]
Also notable here is, that text and layout elements without content are not visible in the preview because they have no height yet. 
Please make them also visible by highlighting

**Comment by TheReincarnator** [comment]
Feature has been implemented in 0.7.0.
