### ISSUE TITLE
Request: Publish to Snapstore

### ISSUE THREAD

**Issue by owais** [meetalva/alva#135]
It would be great to have this installed through snap store mainly Ubuntu but also some other Linux distributions. The app looks great and quite promising!

**Comment by LKuechler** [comment]
First of all, thank you for the kind words :)
For now we did not have a real focus on Linux as none of the main developers was working on Linux.
But i will try to look at it in the next weeks.

**Comment by owais** [comment]
Thank you! Linux really lacks a good and moder design/mockup app. I hope this can fill the gap. Best of luck!

**Comment by jedusaad** [comment]
Is there any update about Alva on Linux/Ubuntu?

**Comment by fahrradflucht** [comment]
@LKuechler Is there a way to rename the issue? I was quite confused because there are obviously `.appimage` and `.snap` builds.

**Comment by CiprianStoicescu** [comment]
Hi!
I want to install Alva on Linux but does not find the application through AppImage. What can I do?

**Comment by LKuechler** [comment]
Hi @CiprianStoicescu,
Sorry for taking so long to answer.

You can just download the .appimage file from here: https://github.com/meetalva/alva/releases
If this does not work for you feel free to create a issue. :)
