### ISSUE TITLE
remove `console.log` from code

### ISSUE THREAD

**Issue by Jumace** [meetalva/alva#142]
When you go through the code you'll see that some wild `console.log` function appear.
We 'gotta catch 'em all' ;)

**Comment by tilmx** [comment]
Good point!

**Comment by DanielRuf** [comment]
@Jumace do you plan to start the work on a PR?

**Comment by DanielRuf** [comment]
Imho opinion it makes sense to just run these when we are in dev mode.

**Comment by Jumace** [comment]
No I'm not, thought it would be a nice issue for a first timer

-------- Original message --------

**Comment by DanielRuf** [comment]
@maximilianUE would this be interesting for you?

Just to make sure. Should we completely remove them or just not execute the console.log statements in production.

Do they provide any help in dev mode?

**Comment by LKuechler** [comment]
@DanielRuf for now it should be enough to just remove them. A better way would be done with this issue: #154

**Comment by mimshwright** [comment]
I'll work on this. 

You might want to consider adding a linter rule that throws a warning for `console` then run your linter as a precommit hook.

**Comment by TheReincarnator** [comment]
Removed all console.logs, replacing some with info, warn, or error, and removing some entirely.
