### ISSUE TITLE
Do we have a support for Ubuntu Please? 🤔

### ISSUE THREAD

**Issue by touqeershafi** [meetalva/alva#145]

**Comment by LKuechler** [comment]
For now we could not test if Alva works correctly on ubuntu.
The AppImage file in releases should be the executable for linux. You can try if you want :)
https://github.com/meetalva/alva/releases/download/v0.6.0/meetalva-0.6.0-x86_64.AppImage

**Comment by RohanAsmat** [comment]
I am trying it on ubuntu, can you please elaborate the steps to make it executable?

**Comment by ruudz** [comment]
@RohanAsmat, right-click on the AppImage -> Properties -> Permissions and check 'Allow executing file as program'.

**Comment by RohanAsmat** [comment]
Hi @ruudz,

Thanks for the information, that worked ! 

Best Regards,
Muhammad Rohan Ali Asmat
