### ISSUE TITLE
Save indicator

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#146]
When I made changes to a page and did not save yet, I expect an "Edited" note in the chrome next to the project name, so I now I have to save my page. See behaviour e.g. in Sketch (attached).

<img width="231" alt="bildschirmfoto 2017-12-22 um 15 04 59" src="https://user-images.githubusercontent.com/8946766/34300696-84e6e852-e729-11e7-9e57-6097447037c1.png">

Besides that, when closing Alva with an unsaved Project, the user should be warned with an "This file has unsaved changes" and asked, if he wants to save or drop the changes:

<img width="534" alt="savechanges" src="https://user-images.githubusercontent.com/8946766/40224406-5c9c83b8-5a86-11e8-801c-84ce6c8c8db6.png">

**Comment by marionebl** [comment]
Obsolete via https://github.com/meetalva/alva/pull/486
