### ISSUE TITLE
More shortcuts for page elements

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#148]
We need some more keyboard shortcuts to manage the page elements more easily:

- [ ] Press [Arrow-Left] to close a parent element (like clicking on the arrow)
- [ ] Press [Arrow-Right] to open a parent element (like clicking on the arrow)
- [ ] Press [Arrow-Down] to jump to the following element
- [ ] Press [Arrow-Down] to jump to the previous element
- [ ] Press [Escape] to jump to the parent element (if root level reached -> unselect element)

**Comment by LKuechler** [comment]
What about [Arrow-Up] and [Arrow-Down] to navigate from one sibling to the next?

**Comment by tilmx** [comment]
Not sure if we should use arrow up/down for page scrolling in the preview pane... We could also depend the shortcuts on the pane you are actively working in.
