### ISSUE TITLE
Hide a page element

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#152]
As a user I want to have an option to hide a page element. The element should stay shown in the page element list, but hidden in the preview pane.

With this features, designers can try out different states (different elements hidden/shown) of a page without losing all the entered properties by deleting the element.

This features should be accessible via Context Menu (right-click on element) and an visual indication next to the element inside the element list (design tbd).

**Comment by marionebl** [comment]
Implemented by introduction of the builtin conditional component
