### ISSUE TITLE
Create Logger concept

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#154]
For proper debugging when developing and also when debugging incoming issues we need to have the ability to get more information.

We should create a basic concept on how we can manage this without to much overhead.

**Comment by marionebl** [comment]
With the move to encapsulated `.alva` files and the addition of stack trace error reporting we can handle bug reports without resorting to log files.

**Stack Trace Reporting**:

https://github.com/meetalva/alva/blob/eeb0cbf6d46962c81d417790c1a9fba189697886/src/electron/create-github-issue-url.ts
