### ISSUE TITLE
Delete project

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#16]
As a user I want to be able to delete a project

**Comment by kotzendekrabbe** [comment]
#83

**Comment by kotzendekrabbe** [comment]
#83

**Comment by LKuechler** [comment]
@kotzendekrabbe i think its just in progress and not yet completely done. Or did i miss a PR? :)

**Comment by kotzendekrabbe** [comment]
@LKuechler no my fault, clicked on close and comment instead of comment

**Comment by markusoelhafen** [comment]
A project can only be deleted on the project overview (#216).
To delete a project you have 3 options:
- Context Menu (Right click) -> "Delete Project"
- Main Menu -> Edit -> "Delete"
- Shortcut "⌫"

**Click Flow:**
![deleteproject](https://user-images.githubusercontent.com/10544994/37591946-71d4b2e8-2b6d-11e8-9b21-55d1a812338d.png)

**Comment by tilmx** [comment]
Closed due to our upcoming change to .alva files. You can delete them by yourself then in Finder/Explorer.
