### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#160]
As a user I want to rename a project.

**Comment by markusoelhafen** [comment]
From a ux point we have multiple options here.

1. allowing renaming only on the project overview page <img width="703" alt="screen shot 2018-01-26 at 16 46 36" src="https://user-images.githubusercontent.com/10544994/35447647-8a9c51a6-02b8-11e8-833b-ed6b9ebbc843.png">

2. double click the project name in the title bar. The title becomes an input field and is saved on enter. <img width="903" alt="screen shot 2018-01-26 at 16 46 07" src="https://user-images.githubusercontent.com/10544994/35447659-908328ba-02b8-11e8-868e-bb7c967ff730.png">

3. click on project name in title bar opens dropdown with multiple options. one option is renaming. title becomes input field and is saved on enter. <img width="386" alt="screen shot 2018-01-26 at 16 46 44" src="https://user-images.githubusercontent.com/10544994/35447667-955350f4-02b8-11e8-9453-bfa6f104cb4d.png">


Personally I would opt for renaming only on project overview page. So each page has its dedicated function. 
What do you think @tilmx ?

**Comment by markusoelhafen** [comment]
We decided to go with **option 1**. Renaming Projects will only be possible on the Page Overview (#176 )

**Comment by tilmx** [comment]
Closed due to our upcoming change to .alva files. You can rename them by yourself then in Finder/Explorer.
