### ISSUE TITLE
Bugs && Suggestions

### ISSUE THREAD

**Issue by chrismcclellan** [meetalva/alva#162]
- When selecting `Preferences` from the `Alva` topbar menu - nothing happens.
- No way to delete or remove elements. I tried dragging, right-clicking, scanning the whole app ui.
  (Just figured it out... delete key. If can create with GUI should be able to delete with GUI)
- Naming elements / layers (or assigning an `id` of sorts)
- Unable to add new elements. I believe after `Create Styleguide` and then canceling.

Awesome start though! I'll be following the progress for sure.

**Comment by LKuechler** [comment]
Hi @chrismcclellan, thanks for the great suggestions.
With the preferences you are absolutely right that something should happen on that button but at the moment we don't really have anything that can be configured. I am pretty sure we will have something there in the feature and i will create a specific issue for that. Thanks for reminding us :)

For the deletion/removing of elements we already have a ticket for a context menu (#111). Maybe thats not enough and we have to create a directly visible gui element for that.

Can you clarify what you mean with "Naming elements"? The name of the elements should be based on how they are named in the styleguide or do you mean that a nickname can be assigned?

What do you mean with "Unable to add new elements"? New elements like a button or a input should probably be created in the styleguide with tools that can more specifically support the developer in doing so.

Thank you again for bringing up all of these points.

**Comment by mikehobi** [comment]
I think element nicknames would be nice. It's beneficial for viewing the project structure at a glance in the layer menu: ex. "Welcome Header", "Pricing Module".

Currently, you have to poke around at layers to figure it out (element highlighting will also help)

**Comment by TheReincarnator** [comment]
As a reference, these are the issues for the above points:
* Preferences: #164 
* Delete/add elements: In the page-elements pane (top-left), right-click should work. In the preview, no interaction is possible yet, this is #129, #130, #131, #180 
* Naming elements: #205 

Thanks for the issue reports!
