### ISSUE TITLE
Preference layer

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#164]
The preference button should open a layer with future configurations for alva.
As long as we don't have any configurations we could show a placeholder or just remove the button completely

**Comment by tilmx** [comment]
The dark mode setting #165 should be included here, too.

**Comment by LKuechler** [comment]
@markusoelhafen @tilmx could we have a very basic design how this could look? Or should it just be oriented on a different application? :)

**Comment by markusoelhafen** [comment]
As the preference button has been removed and we currently have no use for preferences, this issue could be removed from the beta project, or closed entirely.
@LKuechler @tilmx do you agree?

**Comment by marionebl** [comment]
Going through with @markusoelhafen suggestion
