### ISSUE TITLE
Evaluate different Linux distribution methods

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#166]
We already have a simple appimage file for distributing to linux but we also have the feedback that other solutions are simpler and have a higher adoption. ( #163 and #135 )

It should be evaluated how to implement the additional build steps without to much additional work.

**Comment by marionebl** [comment]
We'll do the following:

* [x] Provide `alva-appimage` to Arch users, an AUR wrapper for our "stable" appimage build based on tags: https://github.com/meetalva/aur-alva-appimage
* [x] Provide `alva-git` in joint work with @gunar,  an AUR wrapper for our "development" source build based on master HEAD: 
https://github.com/meetalva/aur-alva-git
* [ ] Provide a `.deb` package for Ubuntu, Mint with a "stable" build based on tags
* [ ] Publish our `.snap` build to snapstore [automatically](https://gist.github.com/evandandrea/c754964bfdfb176844f26f605ebbb8db)

---
In related news we could automate our releases by building and publishing new ones automatically for git tags on master.
