### ISSUE TITLE
Changelog on update

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#167]
When Alva notifies me that a new updates is available, it should tell me what new features are shipped or which bugs are fixed.

**Comment by LKuechler** [comment]
This means it should show the normal changelog that we have with every release? Is that not a bit long?
Maybe we could just add a link to the changelog?https://github.com/meetalva/alva/releases/tag/v0.6.0

**Comment by tilmx** [comment]
Sketch does a pretty good job with displaying hundreds of changes (you can scroll inside the changelog): 
<img width="732" alt="bildschirmfoto 2017-12-24 um 00 38 41" src="https://user-images.githubusercontent.com/8946766/34323311-e5f2f09a-e842-11e7-93c2-5437cd6c7033.png">

**Comment by LKuechler** [comment]
I have to see if we can display the dialog like that but in the worst case we are building our own overlay

**Comment by LKuechler** [comment]
We can get the changelog with `info.releaseNotes` in the `update-available` listener.
I could not find a way to build a dialog with a scroll area like the one from sketch but maybe we could build a custom one. As a new window or maybe with the help of a library: https://www.npmjs.com/package/electron-modal
