### ISSUE TITLE
Mac: Homebrew Cask

### ISSUE THREAD

**Issue by douglasmiranda** [meetalva/alva#169]
At some point it would be nice to have Alva available on Homebrew.

https://github.com/caskroom/homebrew-cask

**Comment by agustif** [comment]
I've gone ahead and added a PR to hombrew/cask https://github.com/caskroom/homebrew-cask/pull/42292

**Comment by LKuechler** [comment]
@agustif thanks for doing helping out with this issue :)

**Comment by agustif** [comment]
@LKuechler No problem, I fucked up with git and they had to re-do it again to pass tests, but it's on cask now which is what matters I guess!

I don't have any windows machine right now, but chocolatey is the most aprox thing to cask there's on windows, is alva in there yet? ( A quick google search 'alva site:chocolatey.org' tells me not)

**Comment by LKuechler** [comment]
@agustif Currently i am very far away from my windows test machine but maybe someone that also uses Windows as there main device can test this.  @TheReincarnator

**Comment by TheReincarnator** [comment]
IMHO it is not common on Windows to use package managers. You install software using a setup.exe. That's at least my view after decades of using Windows, both as user and as developer. Windows is a UI-based, not a shell-/terminal-based system.

**Comment by agustif** [comment]
@TheReincarnator 
You should take a look to projects like chocolatey.org, also have in mind Windows recently introduced with a partnership with canonical, a subset of unix commands available from windows terminal...

I think developers using Windows do use package managers too, but maybe I'm wrong
