### ISSUE TITLE
no package-lock.json file but yarn.lock

### ISSUE THREAD

**Issue by DanielRuf** [meetalva/alva#170]
As a developer I want to have the right depencency versions using npm with a provided package-lock.json file.

Is there a reason to have only a yarn.lock file (even if yarn is not used) but ignore the package-lock.json file?

**Comment by LKuechler** [comment]
I don't think it was completely intentional.
We ignored the package-lock because it still has problems with generating differently on different systems. 
I will remove the yarn.lock.
Thanks for the feedback :)
