### ISSUE TITLE
Page overview

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#176]
We need a new additional pages view, so I can get a quick overview of which pages are part of my project. With an right-click I can rename or delete the pages (#111) and with the Add-Icon (+) I can add a new page.

![alva-pages](https://user-images.githubusercontent.com/8946766/34342500-2ec23824-e9b2-11e7-9502-66d65c14faae.png)

**Comment by markusoelhafen** [comment]
**Page Overview – New Project**

This means: 
- Project has no name yet
- One page is automatically created
- This page is also "unnamed"

![page overview new project](https://user-images.githubusercontent.com/10544994/36383597-eb64ec14-158c-11e8-97b9-2bd337b79762.png)
---

**Existing Project**
Project has a name
With named pages

![page overview named project](https://user-images.githubusercontent.com/10544994/36383644-07cd31ae-158d-11e8-875e-f2f12f6aa0b9.png)

---

**Please note:**
- "Add Page" - Button in the bottom right is **not part** of this issue (will get own issue)
- Navigation back to Project Overview is **not part** of this issue (will get own issue)
- "Last saved" information underneath Project name is **not part** of this issue (will get own issue)

**Comment by markusoelhafen** [comment]
**Suggested ToDos:**

- [ ] Pattern Preview Component: 
  - If no preview image src (own issue) --> display placeholder rectangle
  - Display page name / title
- [ ] Project Headline Component:
  - If no name is displayed --> show "unnamed project" and show text in grey + italic
  - If name is specified --> regular Headline Order 3
- [ ] Make Project Headline Editable:
  -  Same functionality as edit page
  - Double click changes name to input
  - Save name on enter

**Comment by markusoelhafen** [comment]
In consultation with @Palmaswell & @TheReincarnator :
**One click** on the page tile: Focus with a blue outline
**Another Click**: Edit the name
**Double click** on the page tile: open page
