### ISSUE TITLE
App is rendered useless when attempting to add component to playground

### ISSUE THREAD

**Issue by chrisopedia** [meetalva/alva#177]
Every time I try to add a component to the Playground the screen blanks to white, the component isn't editable and I can no longer add any elements.  This is just using the newly created space.  I'm on Mac OSX High Sierra.  Turning on developer tools yields this error stack:

```
/Applications/Alva.app/Contents/Resources/app.asar/node_modules/fbjs/lib/warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `PatternListContainer`. See https://fb.me/react-warning-keys for more information.
    in PatternList (created by PatternListContainer)
    in PatternListContainer (created by App)
    in div (created by styled.div)
    in styled.div (created by PatternsPane)
    in PatternsPane (created by App)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div)
    in Unknown (created by App)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div)
    in Unknown (created by App)
    in div (created by styled.div)
    in styled.div (created by Layout)
    in Layout (created by App)
    in App```

**Comment by LKuechler** [comment]
Thanks for bringing this up. The playground (the preview area in the middle) should not be able to get components dropped on them at the moment.
For now only the dropping of components in the Element Tree (the list of components on the left site) is working.

Thanks again for creating this issue

**Comment by chrisopedia** [comment]
Ahh, that makes sense.  The cursor shows the + so it makes me feel like it can.  Thanks for the hard work on this project guys.  This is huge!!!

**Comment by marionebl** [comment]
I dug a bit deeper into this:

1. This happens for external files being dragged onto the preview/app, too.
2. When dragging pattern items outside the svg icon, this does not happen.
3. Dragging the svg icon directly navigates the webview to the svg icon doc

This leaves us with a good news/bad new situation

1. **Good**: File dragging on the main window can pe prevented (as per 0a0c45b4d48e26709aa6581c83a1f1acdfde00a0)
2. **Bad**: File dragging on the webview can't be prevented from outside the webview (reference: https://github.com/electron/electron/issues/1378)
3. **Good**: The icon-dragging effect can be disabled via CSS (PR incoming)
