### ISSUE TITLE
Resize and Hide Left/Right Panels?

### ISSUE THREAD

**Issue by agustif** [meetalva/alva#178]
This could be a good candidate for preferences I guess, but both a clickable ui for resizing and hiding panels would be handy... something like atom would be fine
<img width="342" alt="screenshot 2017-12-26 01 56 14" src="https://user-images.githubusercontent.com/6601142/34343987-f7680484-e9df-11e7-9349-0b98ba182cea.png">

**Comment by LKuechler** [comment]
That sounds very good. Thanks for the suggestion :)

**Comment by agustif** [comment]
Also they could be made more useful using https://github.com/arkenthera/electron-vibrancy

Since a lot of white space ends up on those panels, being able to view what's underneath from your design might be useful

**Comment by LKuechler** [comment]
For electron-vibrancy @markusoelhafen and @tilmx should probably have a look. :)

**Comment by markusoelhafen** [comment]
Hey @agustif! 
Thanks for your suggestion and sorry for this super late answer. The hiding/resizing feature is one that we'll definitely consider in one of our upcoming releases.
As for the vibrancy I'm not a very big fan of blurred backgrounds as it adds some noise that can be distractive in productive tools.

I think for now we should focus on the resizing and hiding of the panes. If we then see the need for some added vibrancy, let's bring it up as a new issue ;)

**Comment by marionebl** [comment]
Resolved via #467
