### ISSUE TITLE
Quit Application does not work as expected

### ISSUE THREAD

**Issue by AnaghSharma** [meetalva/alva#187]
I am not able to quit (cmd + q) Alva when there is no window open. Nothing happens on cmd + q. It works fine if there is an open window.

Steps to reproduce - 
1. Close the current window with **cmd + w**.
2. Try to close the application now with **cmd + q**.

I am on macOS High Sierra 10.13.2.

**Comment by Sigmus** [comment]
I can confirm the bug (El Capitan) 10.11.6 with either clicking the menu or using the cmd + q shortcut.
