### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#19]
As a user I want to create a project inside a styleguide.

**Comment by alxbok** [comment]
@tilmx: I want to work on this issue. I need design / layout for the page.
Also, the following issues #24, #160, #22, #16, #23 and maybe #144 must be considered whilst creating design / layout for the page.

**Comment by tilmx** [comment]
@markusoelhafen Could you take care of the refreshed designs? The current design status is here: https://drive.google.com/open?id=1VXcV2oWxMJEh2S5rLLTFVkdybK1vsx3i
Maybe we should find a "cooler" interaction, when you want to rename a page/project.

**Comment by markusoelhafen** [comment]
Yes, I'll work on the design for the issues.
For deleting pages & projects you can check out @Alexpeschel's PR #83.

**Comment by markusoelhafen** [comment]
This issue has several dependencies on other issues, that need more work in terms of user flow and ux, before getting started. 
We created a flow for "create new project" including the different entry points.

![createproject](https://user-images.githubusercontent.com/10544994/35325549-61860372-00f4-11e8-8b70-5ba24e4037df.jpg)

For creating from an open project, we need to check first if the current project is saved. Part of this is the "edited"-indicator #146 but also an alert if the project is unsaved and will be closed.

Maybe we should work on these issues first and then come back to creating a new project.
