### ISSUE TITLE
Delete elements too easy

### ISSUE THREAD

**Issue by chaosmonster** [meetalva/alva#198]
While working with alva it happened multiple times, that I used the backspace button and thought I am in a text field. Instead I deleted a entire subtree of my site. With a missing undo function this isn't that good.

Feature request:  
I want to be warned if I am deleting a subtree element with X children or depth Y.

**Comment by LKuechler** [comment]
Hi @chaosmonster thanks for the suggestion.
Does this mean that we would only open a dialog when deleting a element with a subtree?
Do we not also already have the problem with a single element when the user thinks he is in a text field?

Do you by chance also have a idea how to make sure the user knows if he is in a textfield or only on a element?
The problem i see is that the user has by definition always a element selected when he changes anything in a textfield

**Comment by tilmx** [comment]
Hey @chaosmonster and @LKuechler!
thanks for the suggestion! I’d say that with the new undo/redo-function #109 it should be easy to revert an accidental deletion. We are currently working on a better design for the property pane, so it may be clearer when you are inside an input and delete just text and when your are outside.
