### ISSUE TITLE
Disable drop zone for "molecules" that can't have child elements

### ISSUE THREAD

**Issue by chaosmonster** [meetalva/alva#199]
The examples provide a molecule called teaser and is possible to create children for that element, but that has no effect on the preview. 

Feature request:  
If an element can't have children remove the ability to drag and drop other elements onto it, so it is not possible to create misleading structures

**Comment by TheReincarnator** [comment]
@faselbaum As you can see in this issue, I still think we need some kind of "allowedPatterns" property in PatternProperty, at least a yes/no flag. This holds for children as well.
