### ISSUE TITLE
Name Components in Element Pane

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#205]
It's pretty confusing to have multiple same components (e.g. Layout) underneath each other in the element pane.

It would be good to have the possibility to name the components (e.g. Layout - "Header Section", "Content Section", ...)

**Comment by TheReincarnator** [comment]
@markusoelhafen Can you please sketch the UI? How do I rename?

**Comment by TheReincarnator** [comment]
@markusoelhafen I have now implemented the store feature, but not the UI. Show should it work? Do you click the element? Is it a context-menu feature only? When editing, is it inline, a dialog? And please consider that the element is a drag-drop hot area already.

**Comment by markusoelhafen** [comment]
@TheReincarnator Renaming can be done in multiple ways.
1. Double-Click on the Element (let me know if this interferes somehow with drag-drop)
2. Context Menu -> "Rename"
3. Main Menu -> Edit -> "Rename"
4. Shortcut -> Cmd/Ctrl+R

The current element name transforms into an input and the Text is already highlighted. On enter the new name is saved. On ESC the old name is used.

How it _could_ look like: 

![renameelement](https://user-images.githubusercontent.com/10544994/38263897-a83968c8-3771-11e8-85ae-5ea1f75c0fa4.png)

**Comment by TheReincarnator** [comment]
@LKuechler Do you maybe have time for this today? The store implementation is done, now only the UI (components incl. LSG) is missing.

**Comment by marionebl** [comment]
Taking over for the UI part
