### ISSUE TITLE
Consistent naming of files regarding dash ("-") and underscore("_")

### ISSUE THREAD

**Issue by TheReincarnator** [meetalva/alva#209]
Currently, we use both, dash ("-") and underscore("_"). In the LSG, dash dominates, while in the rest of Alva, underscore is used.
I vote for using dash ("-") everywhere, with the exception of the CODE_OF_CONDUCT, which is common to have it with underscores.
Agreed?

**Comment by TheReincarnator** [comment]
Files affected:
src\store\page\page_element.ts
src\store\page\property_value.ts
src\store\pattern\parser\pattern_parser.ts
src\store\pattern\parser\typescript_parser.ts
src\store\pattern\property\boolean_property.ts
src\store\pattern\property\enum_property.ts
src\store\pattern\property\number_array_property.ts
src\store\pattern\property\number_property.ts
src\store\pattern\property\object_property.ts
src\store\pattern\property\pattern_property.ts
src\store\pattern\property\string_array_property.ts
src\store\pattern\property\string_property.ts
src\store\pattern\text_pattern.ts
src\store\project\page_ref.ts

**Comment by LKuechler** [comment]
fixed with #210
