### ISSUE TITLE
Project config for changing the path to the build patterns

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#214]
In the project.yaml file it should be possible to change the path where alva searches for all the patterns.

In the moment it searches only in `lib/patterns`

**Comment by mpfeil** [comment]
@LKuechler I can have a look at this issue but I am not sure where to find the `project.yaml`. Or is it the `.alva-prefs.yaml` in the users root folder?

**Comment by TheReincarnator** [comment]
Note: Now the Alva space file (previously referred to as "project config") is alva/alva.yaml.
