### ISSUE TITLE
Alert when unsaved project is about to be closed

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#215]
An alert should appear if the current project is about to be closed (by closing it self, or when opening another project) to warn the user that all his changes will be lost.

![image](https://user-images.githubusercontent.com/10544994/35332505-76304618-010b-11e8-861c-e84b5f16c65b.png)

**Comment by TheReincarnator** [comment]
As we automatically save now when changing pages, this issue is obsolete.
