### ISSUE TITLE
Delete page

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#23]
As a user I want to delete an existing page

**Comment by kotzendekrabbe** [comment]
#83

**Comment by markusoelhafen** [comment]
An existing page can only be deleted on the _page overview_.

First the page needs to be _selected_ (with one click).
There are **3 options to delete a page**:
- _Shortcut_: ⌫
- _Main Menu_: Edit --> 'Delete page'
- _Right Click_: Context menu -> 'Delete page'

Before the deleting the page, an **alert** will show and ask the user if he really wants to delete the page.

**Example Text:**
Are you sure you want to delete "[projectname]"?

**Alert Options:**
"Delete" -> Finally deletes the page
"Cancel" -> cancel action

**Flow:**
![deletepage](https://user-images.githubusercontent.com/10544994/37663376-5fbcb348-2c59-11e8-9995-d4bb89da429e.png)
