### ISSUE TITLE
Switch between Views

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#254]
To go back to page overview (#176)  and project overview (#216) a new navigational elements needs to be implemented.
The element should be placed in the header on the left side.

A small arrow indicates going back and the text should describe the according project or space.

![navigation on page](https://user-images.githubusercontent.com/10544994/36419021-13315c4c-1631-11e8-95f7-61ebfef60251.png)
![navigation on page hover](https://user-images.githubusercontent.com/10544994/36419020-13133bb8-1631-11e8-86d8-6330541539ff.png)

**Note**
In order to make the navigation work, the relevant views need to exist (#176, #216).

**Comment by marionebl** [comment]
Fixed via 75f3c4064690d242eb102a15d14c6d7dd1d19ac4
