### ISSUE TITLE
Skip version update

### ISSUE THREAD

**Issue by TheReincarnator** [meetalva/alva#269]

**Comment by tilmx** [comment]
Maybe this features should be more like a "Skip this version" if I decide this update isn’t worth installing instead of entirely disabling auto-update?

**Comment by LKuechler** [comment]
Currently it is possible to ignore a update for until the app is restarted or the user manually lets Alva check for a update. Is that what should have been done with this issue?

**Comment by tilmx** [comment]
I meant it in a way that the version should be ignored all the time. So like Sketch e.g.:
<img width="732" alt="sketch update" src="https://user-images.githubusercontent.com/8946766/38916858-2c24059e-42e9-11e8-8842-7d902da20a97.png">

**Comment by tilmx** [comment]
Done in latest canary release
