### ISSUE TITLE
WIP: Update preview when pattern code changes

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#27]
... if the component has e.g. a new styling

**Comment by TheReincarnator** [comment]
@tilmx You mean you want to reload the preview? Cmd+R should be sufficient. Or maybe I don't get it.

**Comment by tilmx** [comment]
It was meant that if a pattern has changed (via editing in Code editor etc), Alva detects that and reloads the page-element.

**Comment by TheReincarnator** [comment]
This may be a performance-consuming approach, as we would have to poll on all files regularly. Not too recommended.

**Comment by tilmx** [comment]
Or what about an UI pattern? Like "Sync pattern library" ore something similar? @TheReincarnator

**Comment by TheReincarnator** [comment]
@tilmx Sorry, I already implemented a fast, working solution without the need for any button 😉

**Comment by TheReincarnator** [comment]
Some polish, and the PR is on its way.
