### ISSUE TITLE
Support asset properties (image, file)

### ISSUE THREAD

**Issue by TheReincarnator** [meetalva/alva#274]
The asset is associated directly with the page element, like any other page element value, this issue does not include a central asset management.

**Comment by TheReincarnator** [comment]
@markusoelhafen Can you please make up your mind for a UX here? We have three possible values for asset properties:
* Internal (selected, space-embedded) asset: Choose a file, show a preview
* External (URL, referenced) asset: Enter a URL, show a preview
* Empty: Press clear button to empty the property

Maybe edit the `asset-item/index.tsx` directly?

**Comment by markusoelhafen** [comment]
@TheReincarnator / @LKuechler  **Basic** styling has been applied, can you check the code in `asset-item/index.tsx`?
I left the *clear* button in for now, but we need to think about a general ux/ui for optional properties, so we might not need the clear button in the first place.
