### ISSUE TITLE
Drag-and-drop support for the placeholder component

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#28]
- [ ] I should be able to drag a PNG or JPG from my local folder into the page element layers.

**Comment by kotzendekrabbe** [comment]
Hey @tilmx I don't get the difference between this issue and #29 
Can you explain it? and if it's duplicated close one of them? thank you :)

**Comment by tilmx** [comment]
#29 is about re-ordering page elements and this #28 is about adding a PNG/JPG-placeholder, if the component I want to use in my design is not developed yet.

**Comment by LKuechler** [comment]
@kotzendekrabbe this one is more about the management of additional project ressources and the #13 only considers a extra component for implementing them

**Comment by tilmx** [comment]
Yeah, but it’s true that it may cause some trouble. Should we close this issue as #28 has a more detailed description?

**Comment by LKuechler** [comment]
I see very different problems in both of these issues.
In this one we only have to consider the management and additions to ressources.
In #13 i see way more ui concept problems. Just one of them is that we should probably highlight it as a temporary component.

**Comment by kotzendekrabbe** [comment]
it's totally fine to have both, but then you have to explain the difference better :)
The description field has than to be changed in this issue.
