### ISSUE TITLE
Support Angular Libraries

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#383]
Alva should support not only React.js libraries, but also Angular libraries. We have to evaluate what has to be done for that.

There already was a Open Source Hackathon, see here: https://www.meetup.com/de-DE/SinnerSchrader-Munich-Events/events/248022995/

**Comment by jonyeezs** [comment]
Hi what was the progress at thee meetup?

**Comment by jpidelatorre** [comment]
Is this going to happen? It would be amazing to have.

**Comment by jamie-pate** [comment]
Angular elements may be a middle ground here? :thinking:

**Comment by yuzl** [comment]
will be revisit in the future

**Comment by Danieltech99** [comment]
Would love to see this revisited.
