### ISSUE TITLE
Bad preview performance when editing page elements or properties

### ISSUE THREAD

**Issue by TheReincarnator** [meetalva/alva#402]
Since commit 947f271472 (last-changed date and author, #176 page overview), the preview performance is bad when editing page elements or properties.

The reason is that each change touches the current project, and the current granularity of IPC events triggers a full styleguide reload on the preview side (patterns scan and projects/page-refs deserialization).

Since the change does not affect the patterns path (nor the patterns themselves), the IPC messages should be split into 1. patterns path and analyzer name, 2. projects.

Alternatively, the IPC event should not trigger a patterns reload as the path nor the analyzer changes.

Note: Development on this issue is paused until #389 is merged to reduce conflicts.

**Comment by TheReincarnator** [comment]
@marionebl says it will be fixed by #389 as well.

**Comment by marionebl** [comment]
Fixed via #389 ❤️
