### ISSUE TITLE
Persist sidebar size

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#468]
Alva should remember the last set size for the left and right sidebar. This should be done on application level and independent from the opened project.

## Expected Behavior
So as soon as I set a new sidebar width, Alva saves it – and after closing and re-opening the app, Alva should open with the same sidebar size.

## Expected Benefits
As a user I do not always have to customize the sidebars every time I open Alva. That should save me time.

**Comment by marionebl** [comment]
Implemented with the push of #586
