### ISSUE TITLE
Associate .alva files with Alva

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#469]
Alva should associate .alva files with the application.

## Expected Behaviour
If I double-click on a file in the Finder (macOS) or Explorer (Windows), Alva should open up and try to open that file automatically.

## Expected Benefits
Opening Alva Files is way more easy and is the same ways as known from all other applications (Keynote, Pages, Photoshop, Sketch...)

## Notes
More information here: https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations

**Comment by marionebl** [comment]
Resolved via #517
