### ISSUE TITLE
Undo/Redo on Property Changes

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#470]
Undo and Redo operations currently do not work if I change a property value.

## Current Behaviour
If I change a property value (e.g. Headline Text), blur the input and hit Cmd+Z, it doesn’t revert the property value change. Instead, it reverts the operation before it (and does not touch the value change).

## Expected Behaviour
If I change a property value and hit Cmd+Z/Y, it should revert or repeat the action.

**Comment by marionebl** [comment]
Fixed via https://github.com/meetalva/alva/pull/498
