### ISSUE TITLE
Resizing pointer flickers when hovering resize area

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#471]
Since the new resizing of element / pattern pane, the mouse pointer flickers when hovering. (Draging the panes is still possible, though) 
After 2-3 times, the pointer then works as expected.

![resize-flicker](https://user-images.githubusercontent.com/10544994/40588170-c2fc4008-61d9-11e8-8e0e-23bfe5556b27.gif)

**Comment by marionebl** [comment]
Have we been able to reproduce on a second machine? @tilmx 
Can you still reproduce this @markusoelhafen?

**Comment by markusoelhafen** [comment]
Seems like this issue has been fixed within the current master.
I'll close the issue
