### ISSUE TITLE
Support CSS files

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#551]
We should also support CSS files and not only javascript-styling like styled components. A lot of component libraries work with CSS files – so we should support that, too.

Let’s discuss how to build this – e.g. when connecting a library we could ask for the .css file additionaly – or can we even get the information out of the connected library?

**Comment by kianris** [comment]
What's the status on this issue? We are looking at trying Alva in our team but we will need to find a solution for CSS first.

**Comment by tilmx** [comment]
Hey @kianris – we're still exploring it. For the moment you can use a custom React Helmet Component that injects the CSS file. Would that work for you?

**Comment by kianris** [comment]
Yep that works great, for now I've just created a component that drops a link element directly into the body since Webkit picks it up anyway. Just need to be aware that Electron seems to block file:// links by default so it needs to be a hosted file.
