### ISSUE TITLE
Support for Nested Interfaces

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#562]
We should support nested interfaces like

```
export interface LoremProps {
	lorem: LoremProps;
	ipsum: string;
}
```
to ensure a larger support of properties in projects.
Those nested interface should be displayed with a headline + description (from the JSDoc annotation) and the properties of the interface below.

**Comment by marionebl** [comment]
We kind-of have this via code properties, should we close?

**Comment by tilmx** [comment]
Yeah, let's do that for the moment!
