### ISSUE TITLE
Support for Storybook

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#563]
Because a lot of projects use Storybook as a component library, we should build a connector for it. We might find a way to get the stories from storybook via an API or something else.

**Comment by ndelangen** [comment]
Storybook maintainer here 👋

**Comment by ndelangen** [comment]
I can get you an API that exports the storybook hierarchy

**Comment by marionebl** [comment]
We now support any npm package that exports typed react components and allow for meta data via JSDoc tags. 

Currently there is no mechanism to pull meta information, so I'll close this. Ideas what we could do with such a subsystem are very welcome though - hop on our [Gitter Org](https://gitter.im/meetalva/Lobby) if you want to roll  them around with us. 💬
