### ISSUE TITLE
Double-Clicking on Chrome Buttons leads to Maximize/Unmaximize

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#571]
**Describe the bug**
Double-clicking on chrome buttons leads the same event as double-clicking the entire chrome bar (maximizing or un-maximizing the window).

**To Reproduce**
1. Open Alva Project
2. Double-Click on Layout Switch in Chrome or left or right Page-Switch-Button in Chrome

**Expected behavior**
When double-clicking a button or switch on the chrome bar, the windows should not be maximized or un-maximized. That should only happen, if you double-click on the rest of the chrome area. 

**Screenshots**

**Additional context**
We could test double-click events on e.target, if the user hits the chrome or a specific button on it.

**Comment by marionebl** [comment]
Fixed via #584 
Thanks again @barinali !
