### ISSUE TITLE
Alva creates global webserver for preview, not only local

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#573]
**Describe the bug**
The preview uses a web server via an iFrame for all the preview stuff. That server does not only serve on localhost, but registers as a webserver in the entire network. That leads to the problem that everybody in the same network can access the preview and highlight or click on elements.

**To Reproduce**
1. Create or open an Alva project
2. Take another device that is on the same network
3. Try `[YOUR ALVA DEVICE IP]:1879/preview.html`
4. Do things

**Expected behavior**
Alva should only create the webserver running on localhost, not on the entire network.

**Screenshots**

**Device (please complete the following information):**
 - OS & Version: macOS 10.13.4
 - Version of Alva: master-branch on 42da585

**Comment by barinali** [comment]
I am not so sure if this is a bug. Being served to other network devices is in its nature. To prevent this, network preferences could be changed on the OS or modem level. We could update server to serve the page only if the remote address is equal to the host address (excluding ports).

I have opened a pull request with the approach I mentioned for this. But I am not eager to merge this time. :)

**Comment by marionebl** [comment]
We now create the http server via

https://github.com/meetalva/alva/blob/2770ba66a1ac82a27e9531def15f0255c1364feb/src/server/server.ts#L87

which binds to server to local access only.
