### ISSUE TITLE
failed to load module "gail" and "atk-bridge" on linux mint Tara 19

### ISSUE THREAD

**Issue by GrayCatWhiz** [meetalva/alva#576]
**Install Procedures i've done"**
1.sudo snap install --dangerous alva.snap
(since snap wont allow to install without metadata)
2.snap run alva
**Error occurs when running alva**
```bash
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
[10:46:55.984] [info] App starting...
SNAP env is defined, updater is disabled
```
**Screenshot**
![screenshot from 2018-06-26 10-51-20](https://user-images.githubusercontent.com/24810178/41886486-22cda604-792f-11e8-8c4a-741f285e36c4.png)

**Comment by migueloop** [comment]
Same issue here, trying to use **snap run Insomnia**

**Comment by marionebl** [comment]
Thanks for reporting. Please be aware that Linux support is experimental will Alva still. I'd recommend to build Alva from source in the mean time:
https://github.com/meetalva/alva/issues/633#issuecomment-428846135

**Comment by marionebl** [comment]
We'll look into providing an official `.deb` package and let you know when it is done. :)

**Comment by marionebl** [comment]
Closing this in favor of #166
