### ISSUE TITLE
Alva crashes when it is placed outside of the application folder.

### ISSUE THREAD

**Issue by FabriceSpahn** [meetalva/alva#596]
**Describe the bug**
Alva cannot start when the app is placed in another folder than the application folder.

**To Reproduce**
1. Download 'Alva'
2. Move 'Alva' to any folder except of the application folder
3. Start 'Alva'

**Screenshots**
<img width="426" alt="bildschirmfoto 2018-09-07 um 13 52 32" src="https://user-images.githubusercontent.com/18717383/45218642-a6f31b00-b2a8-11e8-88a1-76e829e5f3a4.png">
Screenshot Alva Error

**Device (please complete the following information):**
 - OS & Version: [e.g. macOS 10.13.6]
 - Version of Alva [Version 0.7.0 (0.7.0)]

**Comment by Jumace** [comment]
Hey Fabrice,

thanks for letting us know that you found a bug 👍 

I tried to reproduce it with the same version of Alva and OS, sadly I couldn't.

Did you verified that the application is working from the Application folder?
If yes, could you try to move Alva to your Downloads or Desktop folder and try again?

I hope we can solve this issue together, thanks again for letting us know.

Have a great Friday
Julian

**Comment by markusoelhafen** [comment]
Hey @FabriceSpahn ,
di

**Comment by markusoelhafen** [comment]
Hey @FabriceSpahn ,
did you try to reproduce to issue with the new version of Alva? Does the issue still occur?

**Comment by FabriceSpahn** [comment]
Hey @markusoelhafen and @Jumace,
I tried to reproduce it several times with the old and now with the new beta version, but it seems like the bug is gone. It works smoothly.
