### ISSUE TITLE
What is a compatible library

### ISSUE THREAD

**Issue by ndelangen** [meetalva/alva#626]
I'm missing documentation on what pattern-library-requirements are.. the link https://github.com/meetalva/alva#pattern-library-requirements on the readme is broken.

**Comment by ndelangen** [comment]
Never mind, found it

**Comment by tilmx** [comment]
Hey @ndelangen! Thanks for reaching out. Let us know if we can help you somehow!
Cheers, Tilman

**Comment by ndelangen** [comment]
Yeah would love to integrate this with storybook, let me know if there's something you'd need from the storybook team to make it happen.
