### ISSUE TITLE
Snap package dektop launcher doesn't work.

### ISSUE THREAD

**Issue by KristijanZic** [meetalva/alva#627]
I've installed the "Alva-0.8.0.snap" package by executing _sudo snap install --dangerous Alva-0.8.0.snap_. 
Launching the app from the terminal by executing _snap run alva_ works completely fine. 

When launching the app trough the desktop launcher tho, I get the following notification:

> Failed to launch "Alva"
> Desktop file didn't specify Exec field

Besides that, everything seems to work as expected. I propose that you publish the beta snap on the [snap store](https://snapcraft.io/) by creating a beta channel for Alva after the desktop file is fixed.

----------------- 
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.18.8-041808-generic 
Uptime: 3 hours, 27 mins 
Packages: 2571 
Shell: bash 4.4.19 
Resolution: 1680x1050 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Communitheme [GTK2/3] 
Icons: Suru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-2400 (4) @ 3.400GHz 
GPU: AMD Radeon RX Vega 
Memory: 3217MiB / 3927MiB

**Comment by marionebl** [comment]
We'll provide official an snapstore upload and a deb package in the future. Progress and discussion for this is tracked in #166
