### ISSUE TITLE
When pasting and duplicating a page element, it shouldn’t be placed as a child but as a following element in the same hierarchy

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#63]

**Comment by LKuechler** [comment]
Does this mean that the pasting of page elements should place the element at the position where a duplicate also would place duplicated elements? @tilmx

**Comment by tilmx** [comment]
@LKuechler Yes, exactly. Same to clicking on an pattern in the patternlist. So when you click on a pattern it should not be placed as a child, but after the previously selected element.
