### ISSUE TITLE
TypeError: Electron.Menu.sendActionToFirstResponder is not a function

### ISSUE THREAD

**Issue by hyrious** [meetalva/alva#630]
**Describe the bug**
removing the elements on the "left element list" with "right click -> delete" causes the error message
however, it works well with <kbd>Del</kbd>

**To Reproduce**
1. drag some element to the element list
2. right click one element
3. "delete"

**Expected behavior**
No error message be shown.

**Screenshots**
![gif](https://user-images.githubusercontent.com/8097890/46352665-ebe25580-c68c-11e8-9c50-59be444beb44.gif)

**Device (please complete the following information):**
 - OS & Version: Windows 10 1803 17134.285
 - Version of Alva 0.8.0

**Additional context**
None.

**Comment by marionebl** [comment]
Thanks for reporting @hyrious. We'll reconfirm on our test devices and post here when we came to a conclusion / fix.

**Comment by jonorozcoc** [comment]
Same
OS: Windows 7 64 bits
Alva: 0.8.0

**Comment by marionebl** [comment]
Should be fixed by revamping our architecture. Please hop on our [Gitter Org](https://gitter.im/meetalva/Lobby) for help if the problem persists.
