### ISSUE TITLE
How to build it from source?

### ISSUE THREAD

**Issue by LinArcX** [meetalva/alva#633]
**Is your feature request related to a problem? Please describe.**
Hi. and thank you for this great application. i am an arch user. and i want to create a __PKGBUILD__ for your app in publish it in [AUR](https://aur.archlinux.org/). But i don't know how to build it from source. can you help me to do it?

**Comment by marionebl** [comment]
You should be able to get an Alva executable like this:

```sh
git clone https://github.com/meetalva/alva.git
# optional: check out the release version
cd alva
git checkout v0.8.0
npm install
npm run build:electron # executables to be found in ./dist
```

**Comment by LinArcX** [comment]
Oh, common, the build process take 20 minutes in my system. :(

**Comment by gunar** [comment]
Beware: `npm run build` need to be executed before `npm run build:electron`

**Comment by tilmx** [comment]
Hey @gunar – cool, thank you very much! 🚀
