### ISSUE TITLE
Website and README do not tell me: What does this sofware DO?

### ISSUE THREAD

**Issue by kindfulkirby** [meetalva/alva#634]
**Describe the bug**
I have looked at the website and the first few dozen lines of the README here, and I still haven't got the faintest idea what this software does. 

"Alva is a radically new digital design tool built for cross-functional product teams."

... so... I can design product teams with it? That can't be right... though, tbf, I'm not sure what  a product team is...
Maybe I (and my team) can design products? What kind of products? Cars? Microwaves?? Telephones???

**To Reproduce**
1. Go to https://meetalva.io/
2. Read the website
3. Know nothing about Alva

**Expected behavior**
A clear and concise description of what Alva is good for.

**Screenshots**
-

**Device (please complete the following information):**
-

**Additional context**

**Comment by marionebl** [comment]
Hey @ttheuer, sorry to hear you did not find the information you were looking for when browsing through the Alva repo. 

Our README is a bit out of date and still containing the old tag line about  "product teams" and being "radically new". 

Until we fix this I'd recommend you use https://meetalva.io/ as reference, where the old tag line is not in use anymore. The current authoritative description of Alva is:

> Alva lets you design interactive products based on components engineered by your developers.

If still in doubt  have a look at the short usage video just below the black stage are on https://meetalva.io/.

Hope that helps

**Comment by ttheuer** [comment]
> Hope that helps

Not really. I don't really care, I was just pointing out that for me - as a lay person who has never had any contact with this project - I am completely *lost* as to what your software does. It is a software, yes?

What are "interactive products"? What are these "components"? The website and the included video don't really tell me _anything_. 

Maybe this thing is targeted at people who already know what it is. That's fine, I guess?

As for me... I am still utterly confused. I don't really care, but I stumbled across this project, so I thought I'd give you some feedback from "the outside".

**Comment by marionebl** [comment]
We worked on our explanations and the site and I hope we now explain better what Alva is supposed to be.
