### ISSUE TITLE
Alternative installation instruction: AUR

### ISSUE THREAD

**Issue by gunar** [meetalva/alva#638]
With [alva-git](https://aur.archlinux.org/packages/alva-git) in place, installing Alva into Arch/Manjaro systems is now just a matter of executing `yaourt -Syy alva-git`.

**Comment by rsteube** [comment]
- `.SRCINFO` needs to regenerated: `makepkg --printsrcinfo > .SRCINFO`
- `git tags` should be a typo
- mac build gives me some troubles, i'd prefer to simply call  `node_modules/.bin/electron-builder -l dir` directly which skips unnecessary targets

```patch
diff --git a/.SRCINFO b/.SRCINFO
index 5977274..13f5817 100644
--- a/.SRCINFO
+++ b/.SRCINFO
@@ -1,16 +1,23 @@
 pkgbase = alva-git
-	pkgdesc = Create living prototypes with code components. 
-	pkgver = 1
+	pkgdesc = Create living prototypes with code components.
+	pkgver = v0.8.0
 	pkgrel = 1
 	url = https://meetalva.io
 	arch = i686
 	arch = x86_64
 	license = MIT
 	makedepends = git
-	depends = glibc
+	makedepends = npm
+	makedepends = nodejs
+	depends = gconf
+	depends = libxss
+	depends = nss
+	depends = gtk3
+	depends = electron
+	depends = libicns
 	provides = alva
 	conflicts = alva
-	source = reredirect-git::git+http://github.com/jerome-pouiller/reredirect.git
+	source = alva-git::git+http://github.com/meetalva/alva.git
 	md5sums = SKIP
 
 pkgname = alva-git
diff --git a/PKGBUILD b/PKGBUILD
index cc7d61b..f97c7b4 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -26,16 +26,16 @@ md5sums=(SKIP)
 pkgver() {
   cd "$srcdir/$pkgname"
 # Use latest tag
-  git tags|tail -n 1
+  git tag|tail -n 1
 }
 
 build() {
   cd "$pkgname"
-  last_tag=$( git tags|tail -n 1 )
+  last_tag=$( git tag|tail -n 1 )
   git checkout $last_tag
   npm install
   npm run build
-  npm run build:electron || true
+  node_modules/.bin/electron-builder -l dir
 }
 
 package() {
```

**Comment by KnisterPeter** [comment]
Unfortunately it fails with the message `npm required`.

**Comment by gunar** [comment]
@rsteube thanks!

1. `.SRCINFO` updated, thanks!
2. Nice catch
3. Agreed, implemented

**Comment by rsteube** [comment]
missed one `tags` at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alva-git#n29
and the `dir` parameter for electron-builder (this one is not necessary, but skips Appimage and Snap)

builds and installs on my machine with `tags` fixed

**Comment by gunar** [comment]
@rsteube done! I'm still getting this error though, do you think it's safe to just ignore it?

![image](https://user-images.githubusercontent.com/7684574/47939506-4b1eca00-dec6-11e8-9406-9bd337a5c87d.png)

**Comment by rsteube** [comment]
yes, that should be fixed with #641 - the dependencies are currently declared as devDependencies and thus missing at runtime.
i also had the electron drag&drop bug before and had to start it with ` --disable-gpu`, but last time i started it i didn't need it

**Comment by rsteube** [comment]
ok, `--disable-gpu` is still necessary for me (might as well add that to the script until the bug is fixed)
@marionebl i can confirm it installs successfully on my machine

**Comment by marionebl** [comment]
@gunar: We'd like to co-maintain the `alva-git` AUR and mirror it here on GitHub. Would you be interested in making me a co-maintainer and get admin permissions on the GitHub mirror in return?

**Comment by gunar** [comment]
@marionebl sure! what's your AUR username?

**Comment by marionebl** [comment]
@gunar I am https://aur.archlinux.org/account/marionebl

**Comment by gunar** [comment]
Woohoo! 
![image](https://user-images.githubusercontent.com/7684574/50184451-5013cd80-02fc-11e9-90cb-395156462283.png)

**Comment by marionebl** [comment]
I added you as collaborator to https://github.com/meetalva/aur-alva-git @gunar. We'll have a look at setting up TravisCI to check the build script and push changes to AUR.

**Comment by marionebl** [comment]
Closing in favor of #166
