### ISSUE TITLE
Update Readme/Installation requirements

### ISSUE THREAD

**Issue by SagaTious** [meetalva/alva#639]
**Is your feature request related to a problem? Please describe.**
Installation requirements are far too high-level.

**Describe the solution you'd like**
Please describe:
- Must be reachable from the central package entry point
What must be reachable? What is a "central package entry point"? Pleas be more concise. Example: "There has to be an index.tsx in the same folder as your package.json", "Set the property [xxx] in your package.json to [xxx]" (if that's what you mean)

- Must be exported via export
What must be exported and where? Each component must be exported? As default or non-default export?

- Must be built with declarations, so a index.d.ts is available
Must be built into what? We're currently developing .tsx files and compiling/bundling creates .d.ts files (I understand you need those) and ES5 .js files currently (what do you need?)

- Supported property types are [XXX]
What about other properties? They'll just be ignored by Alva or do they break anything?

- Pattern Meta Data
Are those mandatory? What does @slot do exactly? I only know this from the web components context. What exactly does @href do?

**Additional context**
Really interested in using Alva. Tried to connect my pattern library. Connected my package.json but no Components seem to be available. I'm missing alot of information about folder structure, necessary properties/configuration, file types etc.

**Comment by tilmx** [comment]
Hey @SagaTious 
Thanks for reaching out and thank you very much for the input! That's a valid point, we’ll have to write them in a more precise way. We'll update the Readme during the next couple of days and might add a guide to the docs.

Just some answers already:

> Must be reachable from the central package entry point

You have to set the "main"-property to your compiled index.js (e.g. for lib/index.js: `"main": "lib/index.js"`). This file or any imported file from there should export all the components.


> Must be exported via export

Each component has to be exported. Alva recognizes both default and non-default exports.


> Must be built with declarations, so a index.d.ts is available

We expect an index.d.ts next to the index.js you specified above in the package.json. 


> Supported property types are [XXX]

Other properties than the supported ones are ignored for the moment.


> Pattern Meta Data

They are not mandatory. If you want to add explanation texts or more specific names you can use the annotations for meta data. @slot forces the property to accept children – in Alva this is displayed in the element tree on the left.

If you want to have a look at an example of a compatible – check out our Designkit: https://github.com/meetalva/designkit

If you’ve got some more questions, let us know!
Cheers,
Tilman

**Comment by marionebl** [comment]
Also, if your library source is publicly available we could have a look and help you out. Improving the docs for developers of components is something we definitely need to improve, we‘ll use your feedback in process 👍

**Comment by marionebl** [comment]
We revamped our online docs quite a bit. There are now

* [Component Library Reference](https://meetalva.io/doc/docs/references/library-requirements.html?guides-enabled=true&m_gmlxsain-enabled=true)
* [Component Library Guide](https://meetalva.io/doc/docs/guides/create-library.html?guides-enabled=true&m_gmlxsain-enabled=true)

I think they should help you getting through the thick of setting up a component lib or adapting an existing one. 

If you still run into problems, there is now also our [Gitter Org](https://gitter.im/meetalva/Lobby) - join us there for help.
