### ISSUE TITLE
Cmd/Ctrl+Z Bugs

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#644]
There are some bugs that happen on reverting the last action via Cmd/Ctrl and Z:

- [x] Property Text Changes
When editing text and instinctively pressing Cmd+Z to undo, Alva undoes the action before that and the new text stays (and isn't replaced by the old one). 

- [x] Re-Order Pages
After re-ordering a page and pressing Cmd+Z the pages randomly change their position. That's weird (https://github.com/meetalva/alva/pull/660) 

- [x] Adding Elements
Add some box elements to a new file and add an image component into each. Press Cmd+Z and you won't be able to add any boxes to the element tree. That shouldn't happen.

**Comment by marionebl** [comment]
>  Property Text Changes
When editing text and instinctively pressing Cmd+Z to undo, Alva undoes the action before that and the new text stays (and isn't replaced by the old one).

Fixed via #657

**Comment by tilmx** [comment]
Still has some bugs, I guess. Try:
1. Create a new file
2. Add Text
3. Change text to "Lorem ipsum"
4. Try Cmd+Z: nothing happens
5. Try Cmd+Z again: Text is deleted entirely...

**Comment by marionebl** [comment]
According to my tests 

>  Adding Elements
Add some box elements to a new file and add an image component into each. Press Cmd+Z and you won't be able to add any boxes to the element tree. That shouldn't happen.

Has been fixed as side catch somewhere along the way
