### ISSUE TITLE
Dragging of components over element lists' elements

### ISSUE THREAD

**Issue by yuzl** [meetalva/alva#646]
**Describe the bug**
While dragging a component over different elements in the element list, the feedback highlight sometimes does not work

**To Reproduce**
1. Drag a component from lib
2. Hover over multiple elements in element list from top to bottom and back while still dragging
4. When hovering over elements from top to bottom the error occurs

**Expected behavior**
While hovering over an element in element ist, the respective element should be highlight.

**Comment by marionebl** [comment]
A screencast of this would help a lot. Any chance the affected element is the last in the list?

Is only "in between" highlight affected or does this happen for the "direct" element highlighting too?

**Comment by yuzl** [comment]
Affected elements are not only last elements. In between highlighting is not affected afaik

<img width="1440" alt="bildschirmfoto 2018-11-08 um 10 30 19" src="https://user-images.githubusercontent.com/4026558/48189854-6b74db80-e341-11e8-8efb-7e1e1788faf8.png">
