### ISSUE TITLE
Use <textarea> instead of <input type="textarea"> for string properties

### ISSUE THREAD

**Issue by markusoelhafen** [meetalva/alva#65]
To better handle larger amounts of text in strings it would be better to switch to a textarea that can be scaled vertically to show more text.

To optimize the height of the textarea it should scale automatically according to how much text is currently entered.
Example: https://codepen.io/vsync/pen/czgrf

To not got overboard with ∞ text length, a maximum should be defined where the textarea can be scrolled.

**Comment by marionebl** [comment]
Solved via push of #586
