### ISSUE TITLE
Closing an Alva file results in dead end

### ISSUE THREAD

**Issue by yuzl** [meetalva/alva#650]
Once the opened alva file is closed (press x in top left corner) the window is closed, alva is still focused in apples top bar, but nothing happens when pressing "File -> new".
"File -> Open" does work.

**To Reproduce**
1. Open an alva file
2. close the window
3. see error

**Expected behavior**
When closing the Alva window, the welcome screen should appear again.

**Comment by tilmx** [comment]
Fixed with #657
