### ISSUE TITLE
Nested Flex boxes

### ISSUE THREAD

**Issue by yuzl** [meetalva/alva#652]
**Describe the bug**
Not sure if bug, but definetly unexpected: If a flex box component is nested inside a flex box component, the width of the nested component is always 100% what ever is entered (Same for height, if flex-direction is set to vertical)

**To Reproduce**
1. Add a flex box, give it width and height
2. Add another flex box and nest this inside
3. Change width

<img width="1541" alt="bildschirmfoto 2018-11-09 um 11 37 49" src="https://user-images.githubusercontent.com/4026558/48257931-3eddc400-e414-11e8-86aa-b3476de24575.png">

**Expected behavior**
I want to change width and height properties of nested containers within a flex box container.

**Comment by tilmx** [comment]
I checked that – that's because of Size: auto. I'll make a PR where the default value is not 'auto' but empty.
