### ISSUE TITLE
Toggle pattern pane

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#69]
As a user I want to be able to toggle the pattern pane, so I only see the "Add pattern" pane if I open it. E.g. like in the screenshot: 
<img width="236" alt="bildschirmfoto 2017-12-17 um 22 26 22" src="https://user-images.githubusercontent.com/8946766/34083995-a7cc1de6-e379-11e7-9323-86cf5dd2996b.png">

**Comment by Jumace** [comment]
Could someone provide more info about this issue?

**Comment by tilmx** [comment]
@Jumace: Yes.
Our intention was, that you do not always need the pattern pane to add new patterns, but sometimes want to have more space for rearranging the page element layers. Thats why we think it would be cool to have an option to toggle the pattern pane.
For now, we don’t have a design for that yet...

**Comment by TheReincarnator** [comment]
Related to #34. We should also enable resizing of the panes, and providing a Chrome-Devtools-like preview document size.

**Comment by TheReincarnator** [comment]
Merged with #178.
