### ISSUE TITLE
Box does not display on canvas for Mac OSX 10.13.2

### ISSUE THREAD

**Issue by cedewey** [meetalva/alva#696]
**Describe the bug**
In trying out the Getting Started tutorial, after adding a box to my canvas' elements, it does not display.

**To Reproduce**
1. Go to 'Essentials`
2. Click on 'Box`
3. Drag 'Box' to 'Elements section'
4. Add background of #DA046E to `Box`

**Expected behavior**
The box does not appear.

**Screenshots**

<img width="1279" alt="alva-no-box" src="https://user-images.githubusercontent.com/1270531/50323705-12e44280-0498-11e9-82f0-db1f2e675429.png">

**Device (please complete the following information):**
 - OS & Version: macOS 10.13.2
 - Version of Alva 0.8.0

**Comment by marionebl** [comment]
I just rechecked your screenshot and realized you added properties to the box element. 
I'll try to be more precise in my answer this time around.

Using the latest build of Alva (0.9.1) gives me the same result with the properties you provided:

<img width="1153" alt="screenshot 2019-01-19 at 21 37 11" src="https://user-images.githubusercontent.com/4248851/51432100-6cc05f80-1c32-11e9-9e61-41f3b5de25d0.png">

As you and I see Alva isn't helpful when elements take an area of zero px^2. We have some ideas on how to provide user feedback for this (e.g. showing a special hint / outline in this case). 

For now you can solve this kind of issue by specifying a height:

<img width="1440" alt="screenshot 2019-01-19 at 21 40 53" src="https://user-images.githubusercontent.com/4248851/51432134-fbcd7780-1c32-11e9-8bbe-8b8b3fadf6cf.png">

Or by adding some content to the box:

<img width="1440" alt="screenshot 2019-01-19 at 21 41 19" src="https://user-images.githubusercontent.com/4248851/51432136-00922b80-1c33-11e9-96cb-f20cf2341d38.png">

I'll close this issue in the meantime - join us in our [Gitter Org](https://gitter.im/meetalva/Lobby) if you need more help.

**Comment by cedewey** [comment]
Thank you very much for the detailed response, it was exactly what I needed.
