### ISSUE TITLE
Adding a new page element leads to false property values

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#70]
When adding another element with the same properties and the new element’s property value is still empty, it shows the value of the other element instead of an empty value

**Comment by kotzendekrabbe** [comment]
@tilmx Would be better to use short "topic/title" and add a detailed description

**Comment by LKuechler** [comment]
@tilmx i just tried it out with the image component from the designkit and could not reproduce it. Could it be that we already fixed this?

**Comment by tilmx** [comment]
Could not reproduce it, too. Let’s close the ticket and if it should happen again, reopen it.
