### ISSUE TITLE
Not able to add sample component library to Alva

### ISSUE THREAD

**Issue by anilkk** [meetalva/alva#710]
**Describe the bug**
Not able to add sample component library to Alva

**To Reproduce**
1. Checkout the sample component library https://github.com/anilkk/sample-component-library-for-alva created using the documentation https://meetalva.io/doc/docs/guides/create-library.html?guides-enabled=true
3. Start Alva. Create a new file (File > New or Cmd+N) Open connect library dialog (Library > Connect New Library or Cmd+Shift+C). Select ~/<location>/sample-component-library-for-alva/package.json. 
4. Components are not added.

**Expected behavior**
HelloWorld component on the left panel should be shown.

**Screenshot**
<img width="1098" alt="screen shot 2018-12-31 at 21 44 17" src="https://user-images.githubusercontent.com/1124415/50567469-75b1c580-0d45-11e9-9648-a573d882a2f2.png">

**Device (please complete the following information):**
 - OS & Version: [e.g. macOS 10.14.1]
 - Version of Alva [e.g. 0.8.0]

**Comment by marionebl** [comment]
Hey Anil, that's because our current docs are anticipating the upcoming Alva release. We should use this as a reminder to add version information to our docs. Thanks for pointing this out.

**Comment by anilkk** [comment]
Tested with Alva 0.8.1, it works fine. So closing this issue.

**Comment by Kr3m** [comment]
Yikes..  Does this mean I should build from Linux source or wait for a new AppImage file to be released?  I'd prefer to use the AppImage, but was wanting to test this software out right away as it seems very promising.

**Comment by Kr3m** [comment]
Is Alva Canary just an alpha version?  Guess I could try that....

**Comment by tilmx** [comment]
Hey @Kr3m! Yes, you can try out the Canary version – every time we commit to the master, the canary release is updated.

**Comment by Kr3m** [comment]
Seems that connecting libraries is completely disabled now...  The menu at the top's options are greyed out ,and clicking on the connect library button does nothing...  Using Ubuntu...

**Comment by tilmx** [comment]
Hey @Kr3m! Hm, looks like a bug. On macOS and Windows it should work. We'll have a look at it, thanks for the report!

**Comment by Kr3m** [comment]
Some progress....  I was able to connect the library by installing the .deb file instead, but now I'm getting a "Sorry, this seems to be an incompatible library" warning.

**Comment by Kr3m** [comment]
Hey no problem.  Outside of that, I really appreciate your hard work.  This seems like a VERY cool app.  I can't wait to use it in production.

**Comment by marionebl** [comment]
Chiming in: The core team is on CET and available on [Gitter](https://gitter.im/meetalva/Lobby). If you want to you can join us there and we'll try to sort this out. <3
