### ISSUE TITLE
Update dev commands in documentation

### ISSUE THREAD

**Issue by zacktayl** [meetalva/alva#752]
Both README.md and CONTRIBUTING.md have incomplete documentation on how to spin up the dev environment for Alva.

## CONTRIBUTING.md 
* Refers to an `npm start` script which does not exist. 
* Recommends using `npm` over `yarn` while I believe the opposite is now true.

## README.md
* Specifies a `yarn lerna run watch` command which does not work

From what I understand, the proper commands to spin up the dev environment are as follows (in separate terminals):
1. `yarn webpack -w`
2. `yarn tsc -b -w`
3. `yarn alva`

I don't mind creating a PR for these! Not sure if there are other places that may need to be updated?

**Comment by tilmx** [comment]
Hey @zacktayl,
you're totally right, we should update it. I just created a PR for that (#753) – do you think it's understandable now?
Cheers,
Tilman

**Comment by zacktayl** [comment]
Looks great, @tilmx!
