### ISSUE TITLE
run in browser

### ISSUE THREAD

**Issue by pouyamiralayi** [meetalva/alva#756]
Hi there! is it possible to port this project to browser?
thanks in advance.

**Comment by tilmx** [comment]
Hey @pouyamiralayi!
You can run most of the features of Alva (except local library connect) also in the browser. Just run in the folder of your repository:

First terminal window: `yarn tsc -b -w`
Second terminal window: `yarn webpack -w`
Third terminal window `yarn alva --host=node`

Then you should be able to open the URL shown in the third terminal window in your browser.
Does that work for you?

Cheers
Tilman

**Comment by pouyamiralayi** [comment]
Hello @tilmx  great thanks for your kind answer and support. it works like a charm. this project seems very promising. thanks in advance.
