### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by levirs565** [meetalva/alva#778]
Hey there, I just encountered the following error with Alva:

```

```

<details><summary>Stack Trace</summary>

```
Error
    at getBundle (C:\Program Files\Alva Canary\resources\app.asar\index.js:276077:23)
```

</details>

**Comment by tilmx** [comment]
Hey @levirs565, it looks like you tried to connect a library that is not compatible. Can you share the library with us so we could have a look at it?

We are working on a better error management when importing a library, so that it easier to see what didn't work.

**Comment by levirs565** [comment]
I tried to using @meetalva/material-design library from npm
