### ISSUE TITLE
New Pages are duplicated

### ISSUE THREAD

**Issue by johanfjr** [meetalva/alva#779]
Hey there, I just encountered the following error with Alva:
Whenever I want to add a page, It'll add the page twice (in a click).

I use the Elementary OS 5.0 Juno.

**Comment by tilmx** [comment]
Hey @johanfjr – thanks for reaching out! Can you tell us with which Alva version you work with?

**Comment by ealtunyay** [comment]
Same here. Version 1.0.0-alpha.53 on Debian Testing
