### ISSUE TITLE
Link to user guide is down

### ISSUE THREAD

**Issue by sehnsucht13** [meetalva/alva#794]
**Describe the bug**
The link in the README.md which leads to the user guide does not work. It says that the page is not found.

**To Reproduce**
1. Go to README.md
2. Click on `Get Started` or the user guide link
3. See "Page not found" error

**Expected behavior**
Should have link to the user guide or main website of the application rather than an error

**Device (please complete the following information):**
 - Manjaro Linux with Firefox 66.0.5

**Comment by tilmx** [comment]
Good spot! We adjusted the doc structure yesterday but it seems like we forgot to change the links. Thanks!
