### ISSUE TITLE
Library Store - Material UI Broken

### ISSUE THREAD

**Issue by serosthen00b** [meetalva/alva#813]
If i Try to Connect the Material UI, it comes to this error
<details><summary>Stack Trace</summary>

```
Error
    at getBundle (C:\Program Files\Alva Canary\resources\app.asar\index.js:206126:23)
```

</details>

**Comment by IceHacks** [comment]
It's been like this a while.

**Comment by serosthen00b** [comment]
no feedback -- issue closed no fix
