### ISSUE TITLE
Create a contribution documentation

### ISSUE THREAD

**Issue by Jumace** [meetalva/alva#86]
As a developer I want to have a guideline to create a contribution ;)

Seriously would be nice to have such a thing to make it easier for everybody to contribute to this nice project.

**Comment by tilmx** [comment]
Hey @Jumace!
Cool, that you are contributing to Alva. We are currently working on the contribution guide, so stay tuned!
Tilman

**Comment by Jumace** [comment]
Looking forward to it :D
