### ISSUE TITLE
Disable application zooming

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#89]
I can pinch-zoom the application interface (at least on macOS). This shouldn’t happen, so we should fix that.

**Comment by marionebl** [comment]
Are issues closed when landing relevant changes to master or when a new release is cut and downloadable @tilmx?

**Comment by tilmx** [comment]
@marionebl at the moment, when the the PR is merged with the master. Do you think it would make more sense when a new release is out?

**Comment by marionebl** [comment]
No, I am fine either way. Askes to ensure this can be closed.
